plugins {
    id 'java'
    id 'org.springframework.boot' version '3.3.5'
    id 'io.spring.dependency-management' version '1.1.6'
}

configurations {
    developmentOnly
    runtimeClasspath {
        extendsFrom developmentOnly
    }
    compileOnly {
        extendsFrom annotationProcessor
    }
}

group = 'com.pimp'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {

    // AWS SDK v2 BOM (버전은 예시)
    implementation platform("software.amazon.awssdk:bom:2.25.50")
    // swagger
    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.5.0'
    // repository 함수 이름 기반 쿼리 기능
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    // 입력값 조건 정의
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    // Jakarta Validation 지원 Rest Api
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'
    compileOnly 'org.projectlombok:lombok'
    developmentOnly 'org.springframework.boot:spring-boot-devtools'
    annotationProcessor 'org.projectlombok:lombok'
    // Firebase Admin SDK
    implementation 'com.google.firebase:firebase-admin:9.4.3'

    runtimeOnly 'com.mysql:mysql-connector-j'
    implementation 'com.mysql:mysql-connector-j'

    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
}

test {
    useJUnitPlatform()
}