spring:
  datasource:
    url: jdbc:mysql://pimpredata.cb6wsq26at2o.ap-southeast-2.rds.amazonaws.com:3306/project_db?useSSL=false&serverTimezone=Australia/Sydney&characterEncoding=UTF-8&tcpKeepAlive=true&socketTimeout=60000
    username: jemona613
    password: 73U!J3%nEVN67-3
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 600000
      max-lifetime: 1800000
      keepalive-time: 300000
      connection-timeout: 30000
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 772475650410-11h1ldmmh3lntbsrodpa5ffmps70tl43.apps.googleusercontent.com
            client-secret: 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
            scope:
              - openid
              - profile
              - email
              - https://www.googleapis.com/auth/calendar
        provider:
          google:
            issuer-uri: https://accounts.google.com
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true


server:
  port: ${SERVER_PORT:5000}


management:
  endpoints:
    web:
      exposure:
        include: "health,info"
  endpoint:
    health:
      probes:
        enabled: true